module.exports = {
    1: {
        8: {
            name: 'Giải 8',
            smsName: 'G8',
            emailName: 'Giải 8',
            prizeMoney: 100000,
            smsPrizeMoney: '100K',
        },
        7: {
            name: 'Giải 7',
            smsName: 'G7',
            emailName: 'Giải 7',
            prizeMoney: 200000,
            smsPrizeMoney: '200K',
        },
        6: {
            name: 'Giải 6',
            smsName: 'G6',
            emailName: 'Giải 6',
            prizeMoney: 400000,
            smsPrizeMoney: '400K',
        },
        5: {
            name: 'Giải 5',
            smsName: 'G5',
            emailName: 'Giải 5',
            prizeMoney: 1000000,
            smsPrizeMoney: '1tr',
        },
        4: {
            name: 'Giải 4',
            smsName: 'G4',
            emailName: 'Giải 4',
            prizeMoney: 3000000,
            smsPrizeMoney: '3tr',
        },
        3: {
            name: 'Giải 3',
            smsName: 'G3',
            emailName: 'Giải 3',
            prizeMoney: 10000000,
            smsPrizeMoney: '10tr',
        },
        2: {
            name: 'Giải 2',
            smsName: 'G2',
            emailName: 'Giải 2',
            prizeMoney: 15000000,
            smsPrizeMoney: '15tr',
        },
        1: {
            name: 'Giải 1',
            smsName: 'G1',
            emailName: 'Giải 1',
            prizeMoney: 30000000,
            smsPrizeMoney: '30tr',
        },
        0: {
            name: 'Giải ĐB',
            smsName: 'GDB',
            emailName: 'Giải Đặc Biệt',
            prizeMoney: 2000000000,
            smsPrizeMoney: '2 ty',
        },
        10: {
            name: 'Giải phụ đặc biệt',
            smsName: 'GPDB',
            emailName: 'Giải Phụ Đặc Biệt',
            prizeMoney: 50000000,
            smsPrizeMoney: '50tr',
        },
        11: {
            name: 'Giải khuyến khích',
            smsName: 'GKK',
            emailName: 'Giải Khuyến Khích',
            prizeMoney: 6000000,
            smsPrizeMoney: '6tr',
        },
    },
};